### ISSUE TITLE
Transporting wipes lineup

### ISSUE THREAD

**Issue by opn** [fedwiki/wiki-plugin-transport#6] opened 2016-07-17 12:30 UTC
Seems to me that there has been a change in the way the Transporter works with the lineup? Maybe nothing has changed but there is an issue. Dragging and dropping a url opens up a new item in the lineup - but not to the far right of th lineUp it replaces everything to the right of the page with the transporter on it.

This does not seem to work as well for me - I'm trying to transcribe a podcast, and it wipes the page - stopping the recording for instance. What would be great would be to either change it (back) so that it opens a page at the far right of the lineup, or enable a shift toggle to open it up at the end of the lineup on a drop?

**Comment by paul90** [comment] 2016-07-17 14:47
Looks as if the changes in #5 could be the cause.

Think the loss of handling of the shiftkey event in `$page = $(e.target).parents('.page') unless e.shiftKey` at https://github.com/fedwiki/wiki-plugin-transport/commit/480df2c7db65946adafe342c6f482061b9d15f71#diff-cfc390d14889bd70970f4cf33d9b1fa3L38 may be linked

**Comment by WardCunningham** [comment] 2016-07-17 14:56
The shift-click logic when in with 2819fae57b13ddf20b2ef61de2dc21717991bcfe and then out again with 78eecfa53f0f4932698024ae0cd03fcb87168e4c.

I think this must have been a matter of my own hasty coding, temporarily disabling the `event.shiftKey` logic and forgetting to put it back now that there were two paths into the post routine. 

I'm testing a fix now.

**Comment by paul90** [comment] 2019-07-16 14:55
Fixed by #7.

**Closed as completed by paul90** 2019-07-16 14:55 UTC
